### ISSUE TITLE
Consider renaming actions-performed-by-role

### ISSUE THREAD

**Issue by maacl** [agentbellnorm/dativity#1]
Lovely work and very clean and understandable code.

May I suggest renaming `actions-performed-by-role`. I immediately assumed that it would return the actions actually performed by a certain role, as opposed to the actions allowed by a specific role. This especially because of `actions-performed` which returns all performed actions.

**Comment by agentbellnorm** [comment]
Thanks!

I totally agree. How about 'actions-allowed-by-role'?

**Comment by maacl** [comment]
That's spot on I think.

**Comment by agentbellnorm** [comment]
Implemented in 2.0.0

Closing the issue.
